# Spring Boot Application Configuration
spring.application.name=Service Management System

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.cs320=DEBUG
logging.level.org.springframework.web=INFO
